### PR TITLE
renamed stat-based load balancer to least-response-time

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by Ladicek** [comment]
As a nitpicker, I have to point out that the package name is `responsetime`, and the class name is `LeastLatency`. Latency and response time, while often used interchangeably, are actually two different things :-)

**Comment by michalszynkiewicz** [comment]
> As a nitpicker, I have to point out that the package name is `responsetime`, and the class name is `LeastLatency`. Latency and response time, while often used interchangeably, are actually two different things :-)

good catch, will fix it

**Comment by michalszynkiewicz** [comment]
@Ladicek fixed

**Comment by Ladicek** [comment]
Ah sorry, I wasn't clear. What you measure is actually response time, not latency :-) But then, as I said, the two terms are often used interchangeably, so as long as the codebase is internally consistent, it's fine. Nitpicker logging off :laughing:

**Comment by michalszynkiewicz** [comment]
> Ah sorry, I wasn't clear. What you measure is actually response time, not latency :-) But then, as I said, the two terms are often used interchangeably, so as long as the codebase is internally consistent, it's fine. Nitpicker logging off

Hmmm... at first I just wanted to make it consistent. But maybe I should rename to `least-response-time`. It's not that long and closest to true (only omits the fact that we treat errors even worse than long response times)

**Comment by michalszynkiewicz** [comment]
@cescoffier how do you like `least-response-time`?

**Comment by cescoffier** [comment]
+1

**Review by aureamunoz — APPROVED** [review]

**Pull request merged**
