### PR TITLE
🦈 add resolve-srv option 🦈

### LINKED ISSUE #548: Allow DNS SRV skip resolve
During DNS SRV service lookup, A + AAAA records are automatically resolved. Allow users to optionally skip this resolution step so that non-resolved services names are returned if desired.

### PR DESCRIPTION
**Pull request by eformat**
WIP - fixes #548 
- need to add some tests
- add to docs

### CODE REVIEW

**Comment by cescoffier** [comment]
Nice!

**Comment by eformat** [comment]
added Tests and Doco
cc: @cescoffier

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@eformat I've (force) pushed a few changes:

- revapi justification
- make the test a bit more robust

Let's see what the CI says, but I think it's good to go.

**Comment by cescoffier** [comment]
Thanks!

**Comment by eformat** [comment]
thanks @cescoffier 👍

**Pull request merged**
