### PR TITLE
'use-secure-random' attribute

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by aureamunoz — CHANGES_REQUESTED** [review]
The documentation would be missing, except that LGTM!

**Comment by cescoffier** [comment]
The attribute is going to be part of the documentation table, so included in each load-balancer page. I don't believe we need a section about that parameter.

**Comment by cescoffier** [comment]
Actually... no, the tables are not copied in the LB. Fixing...

**Comment by cescoffier** [comment]
@aureamunoz fixed!

**Review by aureamunoz — APPROVED** [review]
LGTM!

**Pull request merged**
